// Objective-C API for talking to github.com/eycorsican/go-tun2socks-mobile Go package.
//   gobind -lang=objc github.com/eycorsican/go-tun2socks-mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Tun2socks_H__
#define __Tun2socks_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol Tun2socksPacketFlow;
@class Tun2socksPacketFlow;

@protocol Tun2socksPacketFlow <NSObject>
- (void)writePacket:(NSData* _Nullable)packet;
@end

FOUNDATION_EXPORT void Tun2socksInputPacket(NSData* _Nullable data);

FOUNDATION_EXPORT void Tun2socksStartSocks(id<Tun2socksPacketFlow> _Nullable packetFlow, NSString* _Nullable proxyHost, long proxyPort);

@class Tun2socksPacketFlow;

@interface Tun2socksPacketFlow : NSObject <goSeqRefInterface, Tun2socksPacketFlow> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)writePacket:(NSData* _Nullable)packet;
@end

#endif
